---
aws:
  common:
    region: ap-northeast-1
  vpc:
    name: AnsibleVPC
    cidr_block: 10.0.0.0/16
    tags:
      Name: AnsibleVPC
    igw:
      tags:
        Name: AnsibleIGW
    subnet:
      subnet1:
        tags:
          Name: public-a
        cidr: 10.0.1.0/24
        zone: a
    route_table:
      tags:
        Name: public-route-table

